### ISSUE TITLE
Overlay for 

### ISSUE THREAD

**Issue by alex5250** [Electrics-Eagles/PiElectricsEaglesOS#8]
Code for DTS : 
```
/dts-v1/;
/plugin/;

/ {
	compatible = "brcm,bcm2835";

	fragment@0 {
		target = <&i2cbus>;
		__overlay__ {
			#address-cells = <1>;
			#size-cells = <0>;
			status = "okay";

			sc16is752: sc16is752@48 {
				compatible = "nxp,sc16is752";
				reg = <0x48>; /* i2c address */
				clocks = <&sc16is752_clk>;
				interrupt-parent = <&gpio>;
				interrupts = <24 2>; /* IRQ_TYPE_EDGE_FALLING */
				gpio-controller;
				#gpio-cells = <2>;
				i2c-max-frequency = <400000>;
			};
		};
	};

	fragment@1 {
		target-path = "/";
		__overlay__ {
			sc16is752_clk: sc16is752_i2c_clk@48 {
				compatible = "fixed-clock";
				#clock-cells = <0>;
				clock-frequency = <14745600>;
			};
		};
	};
	
	fragment@2{
		target-path = "/";
		__overlay__ {
			i2cbus: sc16is752-i2c-gpio@0 {
			gpios = <&gpio 23 GPIO_OPEN_DRAIN>,
				<&gpio 24 GPIO_OPEN_DRAIN>;
				compatible = "i2c-gpio";
				i2c-gpio,delay-us = <2>;   

			};
		};
	};
	__overrides__ {
		int_pin = <&sc16is752>,"interrupts:0";
		addr = <&sc16is752>,"reg:0",<&sc16is752_clk>,"name";
		xtal = <&sc16is752_clk>,"clock-frequency:0";
		i2c_gpio_sda = <&i2cbus>,"gpios:4";
		i2c_gpio_scl = <&i2cbus>,"gpios:16";
		i2c_gpio_delay_us = <&i2cbus>,"i2c-gpio,delay-us:0";
	};
};
```

**Comment by alex5250** [comment]
https://user-images.githubusercontent.com/20460747/147394768-57426e5b-b6c3-4f03-9c07-52483d2faf33.mov

**Comment by alex5250** [comment]
For build 
```bash
cpp -nostdinc -I include -I arch  -undef -x assembler-with-cpp  arch/arm64/boot/dts/amlogic/meson-gxl-s905x-khadas-vim.dts meson-gxl-s905x-khadas-vim.dts.preprocessed

dtc -I dts -O dtb -p 0x1000 meson-gxl-s905x-khadas-vim.dts.preprocessed -o kvim1.dtb

kvim1.dtb: Warning (unit_address_vs_reg): Node /scpi/clocks/scpi_clocks@0 has a unit name, but no reg property
kvim1.dtb: Warning (unit_address_vs_reg): Node /soc/bus@c8100000/pinctrl@14 has a unit name, but no reg property
kvim1.dtb: Warning (unit_address_vs_reg): Node /soc/periphs@c8834000/rng has a reg or ranges property, but no unit name
kvim1.dtb: Warning (unit_address_vs_reg): Node /soc/periphs@c8834000/pinctrl@4b0 has a unit name, but no reg property
kvim1.dtb: Warning (unit_address_vs_reg): Node /soc/periphs@c8834000/eth-phy-mux has a reg or ranges property, but no unit name
kvim1.dtb: Warning (unit_address_vs_reg): Node /gpio-keys-polled/button@0 has a unit name, but no reg property
kvim1.dtb: Warning (simple_bus_reg): Node /soc/bus@c8100000/pinctrl@14 missing or empty reg/ranges property
kvim1.dtb: Warning (simple_bus_reg): Node /soc/periphs@c8834000/rng simple-bus unit address format error, expected "0"
kvim1.dtb: Warning (simple_bus_reg): Node /soc/periphs@c8834000/pinctrl@4b0 missing or empty reg/ranges property
kvim1.dtb: Warning (simple_bus_reg): Node /soc/periphs@c8834000/eth-phy-mux simple-bus unit address format error, expected "55c"
```

**Comment by alex5250** [comment]
https://stackoverflow.com/questions/50658326/device-tree-compiler-not-recognizes-c-syntax-for-include-files

**Comment by alex5250** [comment]
/dts-v1/;
/plugin/;
/include/ "gpio.h"
/ {
	compatible = "brcm,bcm2835";

	fragment@0 {
		target = <&i2cbus>;
		__overlay__ {
			#address-cells = <1>;
			#size-cells = <0>;
			status = "okay";

			sc16is752: sc16is752@48 {
				compatible = "nxp,sc16is752";
				reg = <0x48>; /* i2c address */
				clocks = <&sc16is752_clk>;
				interrupt-parent = <&gpio>;
				interrupts = <24 2>; /* IRQ_TYPE_EDGE_FALLING */
				gpio-controller;
				#gpio-cells = <2>;
				i2c-max-frequency = <400000>;
			};
		};
	};

	fragment@1 {
		target-path = "/";
		__overlay__ {
			sc16is752_clk: sc16is752_i2c_clk@48 {
				compatible = "fixed-clock";
				#clock-cells = <0>;
				clock-frequency = <14745600>;
			};
		};
	};
	
	fragment@2{
		target-path = "/";
		__overlay__ {
			i2cbus: sc16is752-i2c-gpio@0 {
			gpios = <&gpio 23>,
				<&gpio 24>;
				compatible = "i2c-gpio";
				i2c-gpio,delay-us = <2>;   

			};
		};
	};
	__overrides__ {
		int_pin = <&sc16is752>,"interrupts:0";
		addr = <&sc16is752>,"reg:0",<&sc16is752_clk>,"name";
		xtal = <&sc16is752_clk>,"clock-frequency:0";
		i2c_gpio_sda = <&i2cbus>,"gpios:4";
		i2c_gpio_scl = <&i2cbus>,"gpios:16";
		i2c_gpio_delay_us = <&i2cbus>,"i2c-gpio,delay-us:0";
	};
};

**Comment by alex5250** [comment]
For compile : 
```
dtc -@ -d gpio.h -I dts -O dtb -o i2c_gpio.dtbo a.dts
``

**Comment by alex5250** [comment]
[overlay.zip](https://github.com/Electrics-Eagles/PiElectricsEaglesOS/files/7776343/overlay.zip)

**Comment by alex5250** [comment]
[devicetree-specification-v0.3.pdf](https://github.com/Electrics-Eagles/PiElectricsEaglesOS/files/7776788/devicetree-specification-v0.3.pdf)

**Comment by ed-ilyin** [comment]
Сколько буковок 😅

**Comment by alex5250** [comment]
Ееее все работает

**Comment by misha-dig** [comment]
Read instruction how compile DT sc16is752 with support any i2c ports: https://github.com/Electrics-Eagles/PiElectricsEaglesOS/tree/master/devicetree/sc16is752-i2c-gpio
